# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubTema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'Tópico',
            },
        ),
        migrations.AddField(
            model_name='tema',
            name='topico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.Topico'),
        ),
        migrations.AddField(
            model_name='subtema',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.Tema'),
        ),
    ]
