# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topico',
            options={'ordering': ['-nombre'], 'verbose_name': 'Tópico'},
        ),
    ]
