# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_auto_20160413_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topico',
            options={'verbose_name': 'Tópico'},
        ),
    ]
